---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
 - Launchpad
 - TV
 - Podcasts
 - 'App Store'
 - Siri
 - Safari
 - Mail
 - Contacts
 - Calendar
 - Notes
 - Reminders
 - Maps
 - Photos
 - Messages
 - FaceTime
 - Pages
 - Numbers
 - Keynote
 - Music
 - Books
 - 'System Settings'
dockitems_persist:
- name: "Microsoft Outlook"
  path: "/Applications/Microsoft Outlook.app/"
  pos: 2
- name: "Spotify"
  path: "/Applications/Spotify.app/"
  pos: 3
- name: "Slack"
  path: "/Applications/Slack.app/"
  pos: 4
- name: "1Password"
  path: "/Applications/1Password.app/"
  pos: 5
- name: "Visual Studio Code - Insiders"
  path: "/Applications/Visual Studio Code - Insiders.app/"
  pos: 6
- name: "iTerm"
  path: "/Applications/iTerm.app/"
  pos: 7
- name: "Microsoft Edge Dev"
  path: "/Applications/Microsoft Edge Dev.app/"
  pos: 8

dotfiles_repo: git@github.com:FinThunderstorm/pistetiedostot.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Configurations/pistetiedostot
dotfiles_files:
  - .zsh.conf
  - .gitconfig
  - .gitignore_global
  - .tmux.conf
  - .osx

homebrew_installed_packages:
  - awscli
  - colima
  - docker
  - docker-buildx
  - docker-compose
  - exa
  - ffmpeg
  - fzf
  - git
  - github/gh/gh
  - jq
  - nano
  - nvm
  - mas
  - pyenv
  - starship
  - terraform
  - tmux

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password-beta
  - 1password-cli-beta
  - adobe-acrobat-reader
  - aerial
  - alfred
  - coconutbattery
  - cyberduck
  - firefox-developer-edition
  - font-comic-mono
  - font-hack-nerd-font
  - gimp-dev
  - insomnia
  - intel-power-gadget
  - iterm2-beta
  - maccy
  - microsoft-edge-dev
  - microsoft-teams
  - rectangle
  - slack-beta
  - sourcetree
  - spotify
  - tunnelblick
  - visual-studio-code-insiders
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 411643860, name: "DaisyDisk (4.24)" }
  - { id: 360593530, name: "Notability (12.1.2)" }
# affinityt
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
